[package]
name = "data-struct-and-algo"
version = "0.1.0"
authors = ["Riley O'Shea <RileyOShea@fairisaac.com>"]

[dependencies]
rand = "0.5.5"
time = "0.1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "week1"
harness = false

[[bench]]
name = "week2"
harness = false
